CREATE TABLE IF NOT EXISTS APPLICATIONS(
    ID UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS APP_RATES(
    ID BIGINT NOT NULL,
    RATE DOUBLE PRECISION NOT NULL,
    RATING_DATE DATE,
    REVIEWER_AGE INTEGER NOT NULL,
    REVIEWER_COUNTRY VARCHAR(3),
    APPLICATION_ID UUID NOT NULL,
    CONSTRAINT FK_RATES_APPLICATION_ID FOREIGN KEY(APPLICATION_ID) REFERENCES APPLICATIONS(ID)
);

CREATE SEQUENCE IF NOT EXISTS APP_RATES_SEQ START 1 INCREMENT 1 NO MAXVALUE CACHE 1;

CREATE INDEX IF NOT EXISTS INDEX_APP_RATES_RATING_DATE ON APP_RATES(RATING_DATE);

